// <auto-generated />
namespace StoryTeller.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedcategoriestable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedcategoriestable));
        
        string IMigrationMetadata.Id
        {
            get { return "201803161044364_Added categories table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
